In [6]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
x,y = load_diabetes(return_X_y=True)

In [9]:
print(x.shape)
print(y.shape)

(442, 10)
(442,)


In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [12]:
print(lr.coef_)
print(lr.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [13]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

In [14]:
y_pred = lr.predict(x_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [15]:
r2_score(y_test,y_pred)

0.4399338661568968

# By using our own class

In [17]:
import random

In [65]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            print(int(X_train.shape[0]/self.batch_size))
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                print(idx)
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [73]:
x_train.shape[0]/50

353

In [69]:
mbr = MBGDRegressor(batch_size=int(x_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [71]:
mbr.fit(x_train,y_train)

50
[43, 88, 212, 148, 287, 196, 26]
[160, 55, 44, 9, 320, 36, 1]
[167, 336, 301, 215, 277, 202, 238]
[155, 177, 147, 166, 216, 307, 288]
[326, 339, 275, 57, 95, 137, 241]
[87, 172, 320, 116, 7, 336, 137]
[88, 270, 73, 204, 311, 71, 287]
[304, 296, 6, 189, 154, 317, 121]
[121, 95, 232, 12, 129, 127, 214]
[167, 285, 233, 86, 271, 351, 205]
[103, 31, 279, 112, 41, 148, 87]
[68, 99, 26, 338, 349, 289, 142]
[211, 42, 282, 41, 335, 103, 197]
[10, 9, 168, 45, 65, 309, 138]
[212, 153, 242, 164, 280, 92, 104]
[224, 107, 166, 227, 81, 328, 254]
[5, 114, 83, 312, 252, 244, 24]
[67, 110, 312, 302, 37, 156, 84]
[190, 341, 135, 309, 50, 32, 316]
[313, 76, 198, 88, 6, 185, 184]
[131, 210, 243, 339, 162, 195, 147]
[279, 216, 73, 62, 268, 29, 272]
[142, 147, 23, 111, 68, 21, 73]
[343, 247, 4, 331, 145, 298, 230]
[4, 158, 248, 219, 14, 233, 60]
[8, 191, 321, 38, 268, 320, 122]
[252, 78, 249, 225, 259, 320, 331]
[43, 73, 41, 247, 235, 236, 316]
[260, 140, 172, 46, 287, 23, 280]
[182, 34, 262, 218, 331, 1

In [22]:
y_pred = mbr.predict(x_test)


In [23]:
r2_score(y_test,y_pred)


0.4547737813184999

In [24]:
from sklearn.linear_model import SGDRegressor


In [25]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.1)


In [26]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [27]:
sgd.coef_


array([  46.98192741,  -61.03879056,  357.5275301 ,  247.94969575,
         25.41269321,  -15.31471329, -172.46913457,  135.66853101,
        301.49581331,  121.72542944])

In [28]:
sgd.intercept_


array([147.3590704])

In [29]:
y_pred = sgd.predict(x_test)


In [30]:
r2_score(y_test,y_pred)


0.42863919402111217