In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [5]:
x,y = load_diabetes(return_X_y=True)

In [7]:
print(x.shape)
print(y.shape)

(442, 10)
(442,)


In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [15]:
print(lr.coef_)
print(lr.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [17]:
y_pred=lr.predict(x_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4399338661568968

# **`Code From Scratch`**

In [26]:
x_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [24]:
x_train[0]

array([-0.00188202, -0.04464164, -0.06979687, -0.01255612, -0.00019301,
       -0.00914259,  0.07072993, -0.03949338, -0.06291688,  0.04034337])

In [90]:
class SGDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0,X_train.shape[0])
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                
                intercept_der = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_



In [92]:
sgd = SGDRegressor(learning_rate=0.01,epochs=40)

In [94]:
import time

In [96]:
start = time.time()
sgd.fit(x_train,y_train)
print("The time taken is",time.time() - start)

155.91101454470618 [  60.40330918  -53.83144785  315.41147525  226.990325     29.60703581
   -9.20215052 -163.22785423  133.21939586  292.45740205  123.33485537]
The time taken is 0.32761406898498535


In [98]:
y_pred = sgd.predict(x_test)
r2_score(y_test,y_pred)

0.4204098127330712

# **`By using sklearn class SGDRegressor`**

` max_iter=100: Sets the maximum number of iterations for the optimization.`
` learning_rate='constant': Uses a constant learning rate, meaning the learning rate remains fixed during training.`
` eta0=0.01: Sets the initial learning rate to 0.01.`

In [104]:
from sklearn.linear_model import SGDRegressor

reg = SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)

reg.fit(x_train,y_train)

SGDRegressor(learning_rate='constant', max_iter=100)
y_pred = reg.predict(x_test)
r2_score(y_test,y_pred)


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1575: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


0.43235723622023925